spring:
  profiles:
    active: ${APP_PROFILE:dev}
  jpa:
    open-in-view: false
  jackson:
    serialization:
      indent-output: true

cors:
  origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}