spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/register-api-db
    username: postgres
    password: 1234567

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

# GENERATE CREATE.SQL
#      jakarta:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#                action: create
#                create-target: src/main/resources/create.sql
    hibernate:
      ddl-auto: none
#      hbm2ddl:
#        delimiter: ;
